### ISSUE TITLE
Incremental saves no longer appearing in Open Recent dialog

### ISSUE THREAD

**Issue by xathian** [bonjorno7/PowerSave#13]
This is only a minor issue but it certainly has messed with a long time muscle memory habit of mine. I've noticed ever since Blender 3.0 release that your recently created incremental saves no longer appear in the File -> Open Recent panel. In 2.93 and prior they appeared, if you were on Project_181 and saved so it created Project_182 then you would see Project_182.blend as the first entry in Open Recent on your next time using Blender, now incremental saves only appear in that dialog if you reopen them first.

Not a huge deal to fix, just a little less convenient having to go open the latest incremental save .blend manually from the folder now.

**Comment by bonjorno7** [comment]
Oh good point, I should fix that.
Not sure why it isn't working but I'll probably figure it out.

**Comment by bonjorno7** [comment]
Pretty sure I fixed this in January, but forgot to close the issue.
I'm also making it so it actually reads the recent files list after writing to it (turns out there's a bpy.ops for it).
