### ISSUE TITLE
Powersave confused by filenames that have numbers in them

### ISSUE THREAD

**Issue by EricEzaM** [bonjorno7/PowerSave#14]
For example, say I am working on a project where I am working on a number of different variants of some object, and I have files named as such:

ObjectVariant1 - Descrption
ObjectVariant2 - Descrption
ObjectVariant3 - Descrption
etc

Using powersave on variant 3 will call the powersave file `ObjectVariant4 - Descrption` - not what is intended.

There should be an option to force powersave to only use the `_01` suffix and ignore all other numbers in the filename.

**Comment by bonjorno7** [comment]
This has been bothering me too actually, I really should do something about it.
It's impossible to read a user's mind, and I don't want it to not recognize version numbers in old files anymore when you change the number format in the settings.
I guess the best solution is to make it an option, Strict Number Recognition or something, which makes it only detect numbers if they follow the scheme set in the preferences.

**Comment by EricEzaM** [comment]
I gave it a shot, I can submit a PR if you are interested.
https://github.com/bonjorno7/PowerSave/compare/main...EricEzaM:PowerSave:support-filenames-with-numbers

> It's impossible to read a user's mind, and I don't want it to not recognize version numbers in old files anymore when you change the number format in the settings.

It does not account for this, it only looks for the pattern currently set. 

https://user-images.githubusercontent.com/41730826/176898636-257b3cfe-7df1-49ac-b46d-1b72e0ef655f.mp4


https://user-images.githubusercontent.com/41730826/176898642-88152f51-10f3-4428-9ea2-6f1a2d3cc27b.mp4

**Comment by bonjorno7** [comment]
I completely forgot to look at your PR, and just did my own implementation.
Anyway I think it works well now.

**Comment by bonjorno7** [comment]
My implementation doesn't support characters after the last number in your Increment Format (it'll append "1"), but I think that's fine; I don't think anybody was doing that anyway.
